sudo: required
dist: trusty

language: node_js

node_js:
  - "5.3"

before_install:
  - rvm install 2.2.3

install:
  - npm install

script:
  - npm test

notifications:
  email:
    - matthew.dingee@opm.gov
