sudo: required
dist: trusty

language: ruby

rvm:
  - 2.2

node_js:
  - "5"

install:
  - npm install

script:
  - npm test

install:
  - npm install

notifications:
  email:
    - matthew.dingee@opm.gov
